[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Created by <a href="https://aryan.app">Aryan Naraghi</a>. Licensed under GNU General Public License.'
